Repository Vermonster/fhir-kit-client, pull requests merged in 2018-04, with the labels that each got.

#3 Add watch tasks for linting and testing
  package.json
  yarn.lock
Labels: enhancement

#4 Error logging
  README.md
  lib/client.js
  lib/logging.js
  lib/smart.js
  package.json
  test/client_test.js
Labels: enhancement

#1 Install coveralls
  .coveralls.yml
  .travis.yml
  README.md
  package.json
  test/client_test.js
  test/fixtures/no-smart-oauth-uri-capability-statement.json
  test/fixtures/valid-capability-statement.json
  yarn.lock
Labels: devops, enhancement

#17 Add nyc to dev-dependencies, replace istanbul with nyc
  package.json
  yarn.lock
Labels: bug, devops

#21 Add code of conduct from contributor-covenant.org
  CODE_OF_CONDUCT.md
  README.md
  package.json
Labels: enhancement

#35 7 - Implement batch and transaction
  docs/fhir-client/0.1.0/Pagination.html
  docs/fhir-client/0.1.0/client.js.html
  docs/fhir-client/0.1.0/global.html
  docs/fhir-client/0.1.0/index.html
  docs/fhir-client/0.1.0/module.exports.html
  docs/fhir-client/0.1.0/pagination.js.html
  docs/fhir-client/0.1.0/reference-resolver.js.html
  docs/fhir-client/0.1.0/smart.js.html
  docs/fhir-client/0.1.0/utils.js.html
  lib/client.js
  test/client-test.js
  test/fixtures/batch-error-request.json
  test/fixtures/batch-error-results.json
  test/fixtures/batch-request.json
  test/fixtures/batch-results.json
  test/fixtures/transaction-error-request.json
  test/fixtures/transaction-error-response.json
  test/fixtures/transaction-request.json
  test/fixtures/transaction-results.json
Labels: enhancement, wip

#45 50: Add batch and transaction examples
  README.md
Labels: enhancement

#47 53: Reorganize launch examples and related readme notes
  README.md
  examples/README.md
  examples/smart-ehr/package.json
  examples/smart-ehr/smart-ehr-launch.js
  examples/smart-ehr/yarn.lock
Labels: enhancement
